"use server";

import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/require-admin";
import { dateKey, parseDateKey } from "@/lib/dates";
import type { ActionResult } from "@/lib/actions/students";

const scheduleItemSchema = z.object({
  dateKey: z.string().min(1, "יש לבחור תאריך"),
  startTime: z.string().regex(/^\d{1,2}:\d{2}$/, "פורמט שעה לא תקין (HH:MM)"),
  endTime: z.string().regex(/^\d{1,2}:\d{2}$/, "פורמט שעה לא תקין (HH:MM)"),
  title: z.string().trim().min(1, "יש להזין כותרת פעילות"),
  groupName: z.string().trim().optional(),
  instructorName: z.string().trim().optional(),
  location: z.string().trim().optional(),
  description: z.string().trim().optional(),
});

export type ScheduleItemInput = z.infer<typeof scheduleItemSchema>;

export interface ScheduleItemRow {
  id: string;
  dateKey: string;
  startTime: string;
  endTime: string;
  title: string;
  description: string | null;
  groupName: string | null;
  instructorName: string | null;
  location: string | null;
}

export interface ScheduleItemActionResult extends ActionResult {
  item?: ScheduleItemRow;
}

function timeToMinutes(t: string): number {
  const m = t.match(/^(\d{1,2}):(\d{2})/);
  if (!m) return 0;
  return Number(m[1]) * 60 + Number(m[2]);
}

function toRow(item: {
  id: string;
  date: Date;
  startTime: string;
  endTime: string;
  title: string;
  description: string | null;
  groupName: string | null;
  instructorName: string | null;
  location: string | null;
}): ScheduleItemRow {
  return {
    id: item.id,
    dateKey: dateKey(item.date),
    startTime: item.startTime,
    endTime: item.endTime,
    title: item.title,
    description: item.description,
    groupName: item.groupName,
    instructorName: item.instructorName,
    location: item.location,
  };
}

function validate(input: ScheduleItemInput): string | null {
  const parsed = scheduleItemSchema.safeParse(input);
  if (!parsed.success) return parsed.error.issues[0]?.message ?? "קלט לא תקין";
  if (timeToMinutes(input.endTime) <= timeToMinutes(input.startTime)) {
    return "שעת הסיום חייבת להיות אחרי שעת ההתחלה";
  }
  return null;
}

export async function updateScheduleItem(
  itemId: string,
  input: ScheduleItemInput
): Promise<ScheduleItemActionResult> {
  await requireAdmin();
  const error = validate(input);
  if (error) return { success: false, error };

  const updated = await prisma.scheduleItem.update({
    where: { id: itemId },
    data: {
      date: parseDateKey(input.dateKey),
      startTime: input.startTime,
      endTime: input.endTime,
      title: input.title,
      description: input.description || null,
      groupName: input.groupName || null,
      instructorName: input.instructorName || null,
      location: input.location || null,
    },
  });

  revalidatePath("/admin/weekly-schedule");
  revalidatePath("/student");
  revalidatePath("/instructor");
  return { success: true, item: toRow(updated) };
}

export async function createScheduleItem(
  weeklyScheduleId: string,
  input: ScheduleItemInput
): Promise<ScheduleItemActionResult> {
  await requireAdmin();
  const error = validate(input);
  if (error) return { success: false, error };

  const created = await prisma.scheduleItem.create({
    data: {
      weeklyScheduleId,
      date: parseDateKey(input.dateKey),
      startTime: input.startTime,
      endTime: input.endTime,
      title: input.title,
      description: input.description || null,
      groupName: input.groupName || null,
      instructorName: input.instructorName || null,
      location: input.location || null,
    },
  });

  revalidatePath("/admin/weekly-schedule");
  revalidatePath("/student");
  revalidatePath("/instructor");
  return { success: true, item: toRow(created) };
}

// Only ever deletes the single ScheduleItem row - there is no relation
// between ScheduleItem and DutyAssignment in the schema, so existing duty
// assignments/publication/completion status are always preserved, never
// touched or regenerated by this action.
export async function deleteScheduleItem(itemId: string): Promise<ActionResult> {
  await requireAdmin();
  await prisma.scheduleItem.delete({ where: { id: itemId } });

  revalidatePath("/admin/weekly-schedule");
  revalidatePath("/student");
  revalidatePath("/instructor");
  return { success: true };
}
