/**
 * MULTI-COURSE (Level-2-only new-trainee slice N1) - PURE, dependency-injected
 * orchestration for ATOMIC creation of a BRAND-NEW, INACTIVE-STAGED Student inside
 * ONE EXPLICITLY identified PLANNED CourseOffering.
 *
 * This module is deliberately NOT a "use server" module and imports NO Prisma
 * client: it is a plain, DB-free server-side library, so the entire business
 * contract is unit-testable without a database (see
 * create-trainee-into-offering-core.test.ts). Every impure capability (the three
 * transaction-local reads and the three writes) is passed in via
 * {@link CreateTraineeTxClient}. The thin real-Prisma binding lives in
 * create-trainee-into-offering.ts.
 *
 * WHAT IT DOES (locked slice-N1 contract):
 *   - Creates a COMPLETELY NEW Student for ONE exact CourseOffering, staged
 *     isActive=false (see the safety rationale below).
 *   - Creates, atomically, exactly THREE rows: Student (isActive=false,
 *     groupName=null, subgroupNumber=null), CourseEnrollment (status ACTIVE,
 *     isPrimary=true because this new person holds exactly one enrollment,
 *     startDate=offering.startDate) and the initial GroupMembership into a proven
 *     leaf subgroup (effectiveFrom=offering.startDate, effectiveTo=null).
 *   - Uses ONLY the exact offering id supplied by the caller. It NEVER resolves an
 *     ACTIVE/current singleton, NEVER reads a selected-course cookie, and NEVER
 *     selects an offering by name/level/"the only planned course".
 *
 * INACTIVE-STAGING (hard safety requirement): the new Student is ALWAYS created
 * isActive=false. The caller cannot supply isActive, and there is NO activation
 * method/flag/helper anywhere in this slice. Rationale: every current Level 1
 * leakage path in the isolation audit is gated by Student.isActive === true. An
 * inactive staged Student cannot log in and is invisible to active Level 1
 * operational rosters, while still being visible through the explicit Level 2
 * CourseEnrollment (offering-scoped readers do not consult Student.isActive).
 *
 * NO COMPATIBILITY MIRROR: unlike the ACTIVE-offering create flow, this slice
 * writes NO Level 1 group compatibility value - groupName and subgroupNumber are
 * always null. The Level 2 group exists ONLY through
 * CourseEnrollment -> GroupMembership -> CourseGroup.
 *
 * WHAT IT NEVER DOES (locked compatibility rule): the {@link CreateTraineeTxClient}
 * surface has NO horse writer, NO legacy studentId-based membership writer, NO
 * Student update/activate method, and NO capability to read or update any Level 1
 * enrollment/membership or any current-offering resolver. The operation is
 * STRUCTURALLY incapable of anything but the three additive writes below, each
 * gated by a transaction-local read proof.
 *
 * TRUST BOUNDARY: this is admin-only infrastructure. It performs NO requireAdmin()
 * itself - a FUTURE server action (a separate slice) MUST call requireAdmin() (and
 * pass an admin-validated route offering id) BEFORE invoking this service.
 *
 * CONCURRENCY (locked): a pre-transaction check is NOT sufficient. Every mutable
 * prerequisite is re-read and re-proven INSIDE the SAME interactive transaction
 * that performs the writes (see runCreateTraineeIntoOfferingInTx). The
 * transaction-local reads are the authoritative proofs; the Student.identityNumber
 * unique constraint is the final backstop against a concurrent duplicate.
 */
import type { CourseOfferingStatus } from "@/app/generated/prisma/client";

// ---------------------------------------------------------------------------
// Public result surface
// ---------------------------------------------------------------------------

/** Stable, non-PII error codes for the new-trainee-into-offering service. */
export type CreateTraineeIntoOfferingErrorCode =
  | "invalid_input"
  | "offering_not_found"
  | "operation_not_allowed"
  | "offering_start_date_missing"
  | "invalid_group"
  | "duplicate_identity"
  | "unexpected";

/**
 * Discriminated result: the newly created Student + enrollment ids, or a stable
 * non-PII error code. It never carries personal data about a matching Student.
 */
export type CreateTraineeIntoOfferingResult =
  | { readonly success: true; readonly studentId: string; readonly enrollmentId: string }
  | { readonly success: false; readonly error: CreateTraineeIntoOfferingErrorCode };

/**
 * The only input this service accepts. Every operational value (isActive,
 * groupName, subgroupNumber, enrollment status, isPrimary, startDate,
 * effectiveFrom) is SERVER-DERIVED, never accepted from the caller, so there is
 * deliberately no such field here. The Student and enrollment ids are generated by
 * the database.
 */
export interface CreateTraineeIntoOfferingInput {
  readonly courseOfferingId: string;
  readonly courseGroupId: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly identityNumber: string;
  readonly phone?: string;
}

// ---------------------------------------------------------------------------
// Input normalization (pure) - mirrors the existing create-trainee convention
// ---------------------------------------------------------------------------

/**
 * The identity-number shape, mirrored EXACTLY from the existing create-trainee
 * validation (studentSchema in lib/actions/students.ts: trimmed, 5-9 digits). It
 * is re-declared locally rather than imported because that rule lives in a "use
 * server" module; keeping a local constant preserves the meaning without importing
 * a Server Action. Any future divergence is a deliberate, reviewable edit here.
 */
export const IDENTITY_NUMBER_PATTERN = /^\d{5,9}$/;

/** The normalized, server-trusted input, or an invalid_input rejection. */
export interface NormalizedCreateTraineeInput {
  readonly courseOfferingId: string;
  readonly courseGroupId: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly fullName: string;
  readonly identityNumber: string;
  readonly phone: string | null;
}

export type NormalizedCreateTraineeResult =
  | { readonly ok: true; readonly value: NormalizedCreateTraineeInput }
  | { readonly ok: false };

/** Trim a value; return null for a non-string / blank / whitespace-only value. */
function trimToNull(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const t = v.trim();
  return t.length === 0 ? null : t;
}

/**
 * Normalize + validate the input (pure), mirroring the existing create-trainee
 * meaning without changing it:
 *   - courseOfferingId / courseGroupId: trimmed, required non-empty (cuids carry
 *     no whitespace);
 *   - firstName / lastName: trimmed, required non-empty (studentSchema min(1));
 *   - identityNumber: trimmed, must match IDENTITY_NUMBER_PATTERN (5-9 digits);
 *   - phone: optional; trimmed, an empty/whitespace/absent value becomes null and
 *     never fails validation (studentSchema keeps phone optional with no format
 *     rule, and stores the trimmed raw value - it is NOT reformatted here);
 *   - fullName: derived deterministically as `${firstName} ${lastName}` trimmed,
 *     matching fullNameOf in lib/actions/students.ts.
 * Any failure returns { ok: false } BEFORE a transaction is ever opened.
 */
export function normalizeCreateTraineeInput(
  input: CreateTraineeIntoOfferingInput,
): NormalizedCreateTraineeResult {
  const courseOfferingId = trimToNull(input?.courseOfferingId);
  const courseGroupId = trimToNull(input?.courseGroupId);
  const firstName = trimToNull(input?.firstName);
  const lastName = trimToNull(input?.lastName);
  const identityNumber = trimToNull(input?.identityNumber);

  if (
    courseOfferingId === null ||
    courseGroupId === null ||
    firstName === null ||
    lastName === null ||
    identityNumber === null ||
    !IDENTITY_NUMBER_PATTERN.test(identityNumber)
  ) {
    return { ok: false };
  }

  const phone = input?.phone === undefined ? null : trimToNull(input.phone);
  const fullName = `${firstName} ${lastName}`.trim();

  return {
    ok: true,
    value: { courseOfferingId, courseGroupId, firstName, lastName, fullName, identityNumber, phone },
  };
}

// ---------------------------------------------------------------------------
// Offering lifecycle classification (pure)
// ---------------------------------------------------------------------------

/**
 * Classify a re-read offering for new-trainee creation (pure). Slice N1 allows
 * PLANNED ONLY (ACTIVE is intentionally rejected even though the broader dormant
 * lifecycle policy permits it; Level 2 must remain PLANNED); ARCHIVED and every
 * other status are blocked. A PLANNED offering with no startDate cannot supply the
 * required effective date. Order matches the error-precedence contract: status
 * before startDate.
 */
export type OfferingCreateClassification =
  | { readonly ok: true; readonly startDate: Date }
  | {
      readonly ok: false;
      readonly error: "operation_not_allowed" | "offering_start_date_missing";
    };

export function classifyOfferingForCreate(
  status: CourseOfferingStatus,
  startDate: Date | null,
): OfferingCreateClassification {
  if (status !== "PLANNED") {
    return { ok: false, error: "operation_not_allowed" };
  }
  if (startDate === null) {
    return { ok: false, error: "offering_start_date_missing" };
  }
  return { ok: true, startDate };
}

// ---------------------------------------------------------------------------
// Duplicate-identity detection (pure) + rollback sentinel
// ---------------------------------------------------------------------------

/**
 * Detect a Prisma unique-constraint violation (P2002) that corresponds to the
 * Student.identityNumber constraint, WITHOUT importing Prisma. The atomic
 * transaction creates a brand-new Student, a brand-new CourseEnrollment, and a
 * brand-new GroupMembership; of every unique constraint they touch, only
 * Student.identityNumber can collide (the enrollment/membership uniques are keyed
 * on the just-created ids, and no CourseGroup is created), so a P2002 whose target
 * cannot be read is still safely attributed to identityNumber. Never inspects or
 * echoes the offending value.
 */
export function isDuplicateIdentityNumberError(err: unknown): boolean {
  if (typeof err !== "object" || err === null) {
    return false;
  }
  const code = (err as { code?: unknown }).code;
  if (code !== "P2002") {
    return false;
  }
  const target = (err as { meta?: { target?: unknown } }).meta?.target;
  if (Array.isArray(target)) {
    return target.some((t) => typeof t === "string" && t.includes("identityNumber"));
  }
  if (typeof target === "string") {
    return target.includes("identityNumber");
  }
  return true;
}

/**
 * Internal signal thrown ONLY when the Student write hits a unique violation on
 * identityNumber (a concurrent duplicate that slipped past the transaction-local
 * pre-read). It is thrown so the real interactive transaction rolls back all
 * writes, and is mapped to `duplicate_identity` by the DI wrapper. Exported solely
 * so that wrapper can `instanceof`-match it across the module boundary; it is not
 * part of the public success/error surface, and it carries no PII.
 */
export class DuplicateIdentityError extends Error {
  constructor() {
    super("A Student already exists with this identity number.");
    this.name = "DuplicateIdentityError";
  }
}

// ---------------------------------------------------------------------------
// Transaction-local IO surface (injected)
// ---------------------------------------------------------------------------

/** The narrow offering shape the transaction-local proof needs. */
export interface TxOfferingRow {
  readonly id: string;
  readonly status: CourseOfferingStatus;
  /** @db.Date UTC-midnight start; nullable in schema, proven non-null here. */
  readonly startDate: Date | null;
}

/**
 * Exact data the single Student write receives. Every containment-critical field
 * is a LITERAL type: isActive is always false, groupName always null,
 * subgroupNumber always null - so the type system itself forbids writing an active
 * or Level 1 group-mirrored Student.
 */
export interface StudentCreateData {
  readonly firstName: string;
  readonly lastName: string;
  readonly fullName: string;
  readonly identityNumber: string;
  readonly phone: string | null;
  /** HARD SAFETY: a newly created Level-2-only trainee is always staged inactive. */
  readonly isActive: false;
  /** No Level 1 group compatibility value is ever written. */
  readonly groupName: null;
  /** No Level 1 subgroup compatibility value is ever written. */
  readonly subgroupNumber: null;
}

/** Exact data the single CourseEnrollment write receives (all server-fixed). */
export interface EnrollmentCreateData {
  readonly studentId: string;
  readonly courseOfferingId: string;
  readonly status: "ACTIVE";
  /** Primary because this new person holds exactly one enrollment. */
  readonly isPrimary: true;
  readonly startDate: Date;
}

/** Exact data the single GroupMembership write receives. */
export interface MembershipCreateData {
  readonly courseEnrollmentId: string;
  readonly courseGroupId: string;
  readonly effectiveFrom: Date;
  readonly effectiveTo: null;
}

/**
 * The injected transaction-scoped boundary. Every method runs INSIDE the same
 * interactive transaction. There is deliberately NO dependency capable of updating
 * or activating a Student, writing a legacy studentId-based membership, writing a
 * TraineeHorseAssignment, touching another enrollment/membership, or resolving the
 * ACTIVE offering: the operation is structurally incapable of anything but the
 * three additive writes below, each gated by a transaction-local read proof.
 */
export interface CreateTraineeTxClient {
  /** Re-read exactly the target offering (id/status/startDate) or null. */
  findOffering: (courseOfferingId: string) => Promise<TxOfferingRow | null>;
  /**
   * Compound leaf-ownership proof: returns the group ONLY when its id matches, it
   * belongs to THIS offering, AND it is a subgroup (parentGroupId not null).
   * Returns null for missing / other-offering / top-level groups alike.
   */
  findLeafGroup: (
    courseGroupId: string,
    courseOfferingId: string,
  ) => Promise<{ id: string } | null>;
  /** Re-read whether a Student already holds this normalized identity number. */
  findStudentByIdentityNumber: (identityNumber: string) => Promise<{ id: string } | null>;
  /** SOLE Student write. A unique violation here means duplicate_identity. */
  createStudent: (data: StudentCreateData) => Promise<{ id: string }>;
  /** SOLE enrollment write. */
  createEnrollment: (data: EnrollmentCreateData) => Promise<{ id: string }>;
  /** SOLE membership write. */
  createMembership: (data: MembershipCreateData) => Promise<{ id: string }>;
}

// ---------------------------------------------------------------------------
// Transaction body (DB-free via injected CreateTraineeTxClient)
// ---------------------------------------------------------------------------

const fail = (
  error: Exclude<CreateTraineeIntoOfferingErrorCode, "unexpected" | "invalid_input">,
): CreateTraineeIntoOfferingResult => ({ success: false, error });

/**
 * The full transaction body: transaction-local proofs THEN the three writes, in a
 * fixed order. Run inside ONE interactive transaction by the caller.
 *
 * Proof order (each returns a stable error BEFORE any write, so an early exit
 * leaves zero rows - the empty transaction simply commits nothing):
 *   1. re-read the exact offering               -> offering_not_found
 *   2. status must still be PLANNED             -> operation_not_allowed
 *      (and startDate must still be present)    -> offering_start_date_missing
 *   3. compound leaf-ownership proof            -> invalid_group
 *   4. no Student may already hold the identity -> duplicate_identity
 *
 * Write order (each after the previous id exists; any THROW aborts the whole
 * transaction so no partial rows survive - a Student-only row can never remain):
 *   5. Student (isActive=false, groupName=null, subgroupNumber=null). A unique
 *      violation on identityNumber -> throw DuplicateIdentityError, which the DI
 *      wrapper maps to duplicate_identity after the transaction rolls back. There
 *      is NO fallback Student creation and NO automatic re-enrollment of a matching
 *      existing Student.
 *   6. CourseEnrollment (ACTIVE, isPrimary=true, startDate=offering.startDate).
 *   7. GroupMembership into the proven leaf subgroup (effectiveFrom=startDate).
 *
 * The enrollment.startDate and membership.effectiveFrom are the SAME
 * offering.startDate, so they never disagree. NO TraineeHorseAssignment and NO
 * legacy TraineeGroupMembership are written.
 */
export async function runCreateTraineeIntoOfferingInTx(
  tx: CreateTraineeTxClient,
  input: NormalizedCreateTraineeInput,
): Promise<CreateTraineeIntoOfferingResult> {
  // 1. Offering re-read (authoritative, transaction-local).
  const offering = await tx.findOffering(input.courseOfferingId);
  if (offering === null) {
    return fail("offering_not_found");
  }

  // 2. Lifecycle + effective-date source, re-proven at write time.
  const classified = classifyOfferingForCreate(offering.status, offering.startDate);
  if (!classified.ok) {
    return fail(classified.error);
  }
  const effectiveDate = classified.startDate;

  // 3. Compound leaf-ownership proof (id AND this offering AND subgroup).
  const group = await tx.findLeafGroup(input.courseGroupId, offering.id);
  if (group === null) {
    return fail("invalid_group");
  }

  // 4. No pre-existing Student with this identity number (friendly pre-check).
  const existing = await tx.findStudentByIdentityNumber(input.identityNumber);
  if (existing !== null) {
    return fail("duplicate_identity");
  }

  // 5. Student write - always inactive-staged, never group-mirrored. The ONLY
  //    unique this create can violate is identityNumber: a P2002 here is a
  //    concurrent duplicate, so throw the sentinel to roll the transaction back
  //    and surface duplicate_identity (no second Student is ever created).
  let student: { id: string };
  try {
    student = await tx.createStudent({
      firstName: input.firstName,
      lastName: input.lastName,
      fullName: input.fullName,
      identityNumber: input.identityNumber,
      phone: input.phone,
      isActive: false,
      groupName: null,
      subgroupNumber: null,
    });
  } catch (error) {
    if (isDuplicateIdentityNumberError(error)) {
      throw new DuplicateIdentityError();
    }
    throw error;
  }

  // 6. Enrollment write - ACTIVE, primary (sole enrollment), startDate=start.
  const enrollment = await tx.createEnrollment({
    studentId: student.id,
    courseOfferingId: offering.id,
    status: "ACTIVE",
    isPrimary: true,
    startDate: effectiveDate,
  });

  // 7. Initial membership into the proven leaf subgroup.
  await tx.createMembership({
    courseEnrollmentId: enrollment.id,
    courseGroupId: group.id,
    effectiveFrom: effectiveDate,
    effectiveTo: null,
  });

  return { success: true, studentId: student.id, enrollmentId: enrollment.id };
}
